declare const describe: any;
declare const test: any;
declare const expect: any;
declare const beforeAll: any;
declare const beforeEach: any;
declare const afterAll: any;
declare const afterEach: any;
declare const jest: any;
declare const process: any;
